CREATE DATABASE IF NOT EXISTS shortener CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shortener;

CREATE TABLE IF NOT EXISTS links (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  short_code VARCHAR(32) NOT NULL UNIQUE,
  long_url TEXT NOT NULL,
  clicks BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_clicked_at TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
